# PHP Docker image for Yii 2.0 Framework runtime
# ==============================================

FROM php:7.0-fpm

# Install system packages for PHP extensions recommended for Phundament
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash - && \
    apt-key update && \
    apt-get update && \
    apt-get -y install \
            g++ \
            git \
            libicu-dev \
            libmcrypt-dev \
            libfreetype6-dev \
            libjpeg-dev \
            libjpeg62-turbo-dev \
            libmcrypt-dev \
            libpng12-dev \
            zlib1g-dev \
            mysql-client \
            openssh-client \
            libxml2-dev \
            nano \
            yui-compressor \
            linkchecker \
            nodejs \
        --no-install-recommends && \
        apt-get clean && \
        npm -g install npm@latest && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install PHP extensions required for Yii 2.0 Framework
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ && \
    docker-php-ext-configure bcmath && \
    docker-php-ext-install gd \
                           intl \
                           pdo_mysql \
                           mbstring \
                           mcrypt \
                           zip \
                           bcmath \
                           soap

# Install PECL extensions
# see http://stackoverflow.com/a/8154466/291573) for usage of `printf`
RUN printf "\n" | pecl install apcu-5.1.3 xdebug-stable && \
    docker-php-ext-enable apcu

# Install less-compiler
RUN npm install -g less lesshint google-closure-compiler

ENV PHP_USER_ID=33 \
    PHP_ENABLE_XDEBUG=0 \
    VERSION_COMPOSER_MERGE_PLUGIN=^1.3.1 \
    VERSION_COMPOSER_ASSET_PLUGIN=^1.2.0 \
    VERSION_PRESTISSIMO_PLUGIN=^0.3.0 \
    VERSION_CODECEPTION=^2.2.6 \
    VERSION_YII2=^2.0.9 \
    PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1

# Add configuration files
COPY image-files/ /

# Add GITHUB_API_TOKEN support for composer
ARG GITHUB_API_TOKEN
RUN echo "alias composer='composer.phar'" >> /root/.bashrc && \
    chmod 700 \
        /usr/local/bin/docker-entrypoint.sh \
        /usr/local/bin/docker-run.sh \
        /usr/local/bin/composer

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer.phar \
        --install-dir=/usr/local/bin && \
    composer global require --optimize-autoloader \
        "wikimedia/composer-merge-plugin:${VERSION_COMPOSER_MERGE_PLUGIN}" \
        "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}" \
        "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" && \
    composer global dumpautoload --optimize

# Install CLI packages required for Yii 2.0 Framework globally
RUN composer global require  --prefer-dist \
        "codeception/codeception:${VERSION_CODECEPTION}" \
        "codeception/specify:*" \
        "codeception/verify:*" && \
    composer global dumpautoload --optimize

# Install Yii 2.0 Framework libraries globally (for build caching)
RUN composer global require  --prefer-dist \
        "yiisoft/yii2:${VERSION_YII2}" \
        "yiisoft/yii2-bootstrap" \
        "yiisoft/yii2-codeception" \
        "yiisoft/yii2-gii" \
        "yiisoft/yii2-debug" && \
    composer global dumpautoload --optimize

# TODO: this is a workaround
RUN composer config --global --unset github-oauth.github.com

WORKDIR /app

# Startup script for FPM
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["docker-run.sh"]
