FROM dmstr/php-yii2:latest

# Install forego (https://github.com/ddollar/forego/releases/tag/20170327195458)
RUN curl -O https://bin.equinox.io/a/c6JW1BqJwSa/forego-20170327195458-linux-amd64.tar.gz \
 && tar -xzf forego-20170327195458-linux-amd64.tar.gz -C /usr/local/bin

# Install nginx
RUN apt-get update \
 && apt-get install -y --force-yes \
            nginx-full \
            cron \
        --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add configuration files
COPY image-files/ /

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log \
 && ln -sf /usr/sbin/cron /usr/sbin/crond

CMD ["forego", "start", "-r", "-f", "/root/Procfile"]

EXPOSE 80 443
