FROM dmstr/php-yii2:7.0-fpm-1.3

# Install Forego
# TODO: use RUN curl ... for better build caching
ADD https://github.com/jwilder/forego/releases/download/v0.16.1/forego /usr/local/bin/forego
RUN chmod u+x /usr/local/bin/forego

# Install nginx
RUN apt-get update && apt-get install -y --force-yes nginx-full

# Add configuration files
# TODO: temporary workaround for missing configs, use separate folder?
COPY image-files/ /

CMD ["forego", "start", "-r", "-f", "/root/Procfile"]

EXPOSE 80 443
